### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by shawnwildermuth** [oslabs-beta/point-of-vue#32]
I couldn't see any examples in the repo. Are there plans to help us understand how it would work? Do we just add it and it will know about our state?

I'm confused.

**Comment by shelbydneuman** [comment]
Hi Shawn - thanks for reaching out to the team. Our read-me lays out how to download our package and integrate it into your Vue3 application that uses the Composition API. If you open the official Vue Chrome devtool, you will see a plugin available for POV. This is documented in our read-me as well and a convenient gif is included that demonstrates this. With the plugin open, you can debug state directly in-browser and use our time travel functionality.
